apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    bandwidthManager:
      bbr: true
      enabled: true
    bpf:
      hostLegacyRouting: false
      masquerade: true
    envoy:
      enabled: true
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
          - BPF
          - NET_ADMIN
          - NET_BIND_SERVICE
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
    loadBalancer:
      algorithm: maglev
    routingMode: tunnel
    tunnelProtocol: geneve
