cni: cilium
disable:
- rke2-canal
- rke2-ingress-nginx
disable-kube-proxy: true
node-external-ip: {{ .PublicIP }}
node-name: {{ .NodeName }}
server: https://{{ .ClusterIP }}:9345
tls-san:
- cluster.local
- {{ .PublicIP }}
token: {{ .Token }}
